baseURL = "https://kelevis.github.io/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "kelevis"
# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"

############ 作者配置 #########################
[author]
name = "kelevis"
email = "kevin.leee1128@gmail.com"
link = "https://kelevis.github.io"

############# 菜单配置 ########################
[menu]
[[menu.main]]
identifier = "posts"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
name = "文章"
url = "/posts/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
weight = 1
[[menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "标签"
url = "/tags/"
title = ""
weight = 2
[[menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "分类"
url = "/categories/"
title = ""
weight = 3
[[menu.main]]
weight = 4
identifier = ""
pre = ""
post = ""
name = "关于我"
url = "/about/"
title = ""

############### 参数配置 ######################
[params]
# DoIt 主题版本
version = "0.3.X"
# 网站图片, 用于 Open Graph 和 Twitter Cards
images = ["./favicon.ico"]
# DoIt 新增 | 0.2.11 开启 PWA 支持
enablePWA = false

################ 搜索配置 ####################
# DoIt 新增 | 0.2.0 搜索配置
[params.search]
#enable = true
## 搜索引擎的类型 ("algolia", "fuse")
#type = "fuse"
## 文章内容最长索引长度
#contentLength = 4000
## 搜索框的占位提示语
#placeholder = ""
## DoIt 新增 | 0.2.1 最大结果数目
#maxResultLength = 10
## DoIt 新增 | 0.2.3 结果内容片段长度
#snippetLength = 50
## DoIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
#highlightTag = "em"
## DoIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
#absoluteURL = false

################# 页面头部导航栏配置 ####################
[params.header]
# 桌面端导航栏模式 ("fixed", "normal", "auto")
desktopMode = "fixed"
# 移动端导航栏模式 ("fixed", "normal", "auto")
mobileMode = "auto"
# DoIt 新增 | 0.2.11 主题切换模式
# 主题切换模式 ("switch", "select")
themeChangeMode = "select"
# DoIt 新增 | 0.2.0 页面头部导航栏标题配置
#[params.header.title]
## LOGO 的 URL
#logo = ""
## 标题名称
#name = ""
## 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
#pre = ""
## 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
#post = ""
## DoIt 新增 | 0.2.5 是否为标题显示打字机动画
#typeit = false

####################################
# 页面底部信息配置
[params.footer]
enable = true
# DoIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
custom = ''
# DoIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
hugo = false
# DoIt 新增 | 0.2.14 托管服务信息 (支持 HTML 格式)
# <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
hostedOn = ''
# DoIt 新增 | 0.2.0 是否显示版权信息
copyright = true
# DoIt 新增 | 0.2.0 是否显示作者
author = true
# 网站创立年份
since = 2019
# ICP 备案信息, 仅在中国使用 (支持 HTML 格式)
icp = ""
# 许可协议信息 (支持 HTML 格式)
#license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

####################################
# 主页配置
[params.home]
# DoIt 新增 | 0.2.0 RSS 文章数目
rss = 10
# 主页个人信息
[params.home.profile]
enable = true
# Gravatar 邮箱, 用于优先在主页显示的头像
gravatarEmail = ""
# 主页显示头像的 URL
# 将你的头像文件放置于 static 或者 assets 目录下
# 文件路径是相对于 static 或者 assets 目录的
avatarURL = "/images/avatar.webp"
#avatarURL = "./pic.jpg"
# 头像的链接指向的 URL
avatarLinkURL = "https://kelevis.github.io"
# DoIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
#title = "It's kelevis Blog site"
# 主页显示的网站副标题
subtitle = "It's kelevis Blog site"
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = true
# DoIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
disclaimer = ""

####################################
# 作者的社交信息设置
[params.social]
GitHub = "kelevis"
Email = "kevin.leee1128@gmail.com"
RSS = true # DoIt 新增 | 0.2.0
#Linkedin = ""
#Twitter = "xxxx"
#Instagram = "xxxx"
#Facebook = "xxxx"
#Telegram = "xxxx"
#Medium = ""
#Gitlab = ""
#Youtubelegacy = ""
#Youtubecustom = ""
#Youtubechannel = ""
#Tumblr = ""
#Quora = ""
#Keybase = ""
#Pinterest = ""
#Reddit = ""
#Codepen = ""
#FreeCodeCamp = ""
#Bitbucket = ""
#Stackoverflow = ""
#Weibo = ""
#Odnoklassniki = ""
#VK = ""
#Flickr = ""
#Xing = ""
#Snapchat = ""
#Soundcloud = ""
#Spotify = ""
#Bandcamp = ""
#Paypal = ""
#Fivehundredpx = ""
#Mix = ""
#Goodreads = ""
#Lastfm = ""
#Foursquare = ""
#Hackernews = ""
#Kickstarter = ""
#Patreon = ""
#Steam = ""
#Twitch = ""
#Strava = ""
#Skype = ""
#Whatsapp = ""
#Zhihu = ""
#Douban = ""
#Angellist = ""
#Slidershare = ""
#Jsfiddle = ""
#Deviantart = ""
#Behance = ""
#Dribbble = ""
#Wordpress = ""
#Vine = ""
#Googlescholar = ""
#Researchgate = ""
#Mastodon = ""
#Thingiverse = ""
#Devto = ""
#Gitea = ""
#XMPP = ""
#Matrix = ""
#Bilibili = ""
#ORCID = ""
#Liberapay = ""
#Ko-Fi = ""
#BuyMeACoffee = ""
#Linktree = ""
#QQ = ""
#QQGroup = ""


############################
# DoIt 更改 | 0.2.0 评论系统设置
[params.page.comment]
enable = true

# Disqus 评论系统设置
[params.page.comment.disqus]
# DoIt 新增 | 0.1.1
enable = false
# Disqus 的 shortname, 用来在文章中启用 Disqus 评论系统
shortname = ""
# Gitalk 评论系统设置

[params.page.comment.gitalk]
# DoIt 新增 | 0.1.1
enable = false
owner = ""
repo = ""
clientId = ""
clientSecret = ""
# Valine 评论系统设置

[params.page.comment.valine]
enable = false
appId = ""
appKey = ""
placeholder = ""
avatar = "mp"
meta= ""
pageSize = 10
lang = ""
visitor = true
recordIP = true
highlight = true
enableQQ = false
serverURLs = ""
# DoIt 新增 | 0.2.6 emoji 数据文件名称, 默认是 "google.yml"
# ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
# 位于 "themes/DoIt/assets/data/emoji/" 目录
# 可以在你的项目下相同路径存放你自己的数据文件:
# "assets/data/emoji/"
emoji = ""

# Waline 评论系统设置
[params.page.comment.waline]
# DoIt 更改 | 0.2.14
enable = false
serverURL = ""
pageview = true
comment = true
 emoji = ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
 meta = ['nick', 'mail', 'link']
 requiredMeta = []
 login = 'enable'
 wordLimit = 0
 pageSize = 10
# imageUploader = false
# highlighter = false
# texRenderer = false

# Facebook 评论系统设置
[params.page.comment.facebook]
enable = false
width = "100%"
numPosts = 10
appId = ""
languageCode = "zh_CN"

# DoIt 新增 | 0.2.0 Telegram Comments 评论系统设置
[params.page.comment.telegram]
enable = false
siteID = ""
limit = 5
height = ""
color = ""
colorful = true
dislikes = false
outlined = false
dark = false

# DoIt 新增 | 0.2.0 Commento 评论系统设置
[params.page.comment.commento]
enable = false
# DoIt 新增 | 0.2.5 Utterances 评论系统设置
[params.page.comment.utterances]
enable = false
# owner/repo
repo = ""
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
darkTheme = "github-dark"
# DoIt 新增 | 0.2.12 Twikoo 评论系统设置
[params.page.comment.twikoo]
enable = false
envId = ""
region = ""
path = ""
cloudbase = true # boolean : true / false. # 是否部署在腾讯云 CloudBase
visitor = true
commentCount = true
# DoIt 新增 | 0.2.12 Vssue 评论系统设置
[params.page.comment.vssue]
enable = false
platform = "github" # ("bitbucket", "gitea", "gitee", "github", "gitlab")
owner = ""
repo = ""
clientId = ""
clientSecret = ""
# DoIt 新增 | 0.2.13 Remark42 评论系统设置
[params.page.comment.remark42]
enable = false
host = ""
site_id = ""
max_shown_comments = 15
show_email_subscription = true
simple_view = false
# DoIt 新增 | 0.2.13 giscus 评论系统设置
[params.page.comment.giscus]
enable = true
# owner/repo
#data-repo="kelevis/kelevis.github.io"
#data-repo-id="R_kgDOLW5GRQ"
#data-category="Announcements"
#data-category-id="DIC_kwDOLW5GRc4Cdz29"
#data-mapping="pathname"
#data-strict="0"
#data-reactions-enabled="1"
#data-emit-metadata="0"
#data-input-position="bottom"
#data-theme="preferred_color_scheme"
#data-lang="zh-CN"
crossorigin="anonymous"
dataRepo = "kelevis/kelevis.github.io"
dataRepoId = "R_kgDOLW5GRQ"
dataCategory = "Announcements"
dataCategoryId = "DIC_kwDOLW5GRc4Cdz29"
dataMapping = "pathname"
dataReactionsEnabled = "1"
dataEmitMetadata = "0"
dataInputPosition = "bottom"
lightTheme = "light"
darkTheme = "dark"
dataLang = "zh-CN"
dataLoading = "lazy"
# artalk 评论系统设置
[params.page.comment.artalk]
enable = false
server = ""
site = ""
lite = false
katex = false
lightbox = false
pageview = true
commentCount = true

# Hugo 解析文档的配置
[markup]
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false
